import { Injectable } from "@angular/core";
import { Observable, of } from "rxjs";
import { map } from "rxjs/operators";
import { Product, Category } from "../models/product.model";

@Injectable({
  providedIn: "root",
})
export class ProductService {
  getFeaturedProducts(limit = 100): Observable<Product[]> {
    return of(this.getSampleProducts().slice(0, limit));
  }

  private getSampleProducts(): Product[] {
    return [
      // Seller 1: Tech Haven (s1) - Electronics
      {
        id: "prod-1", title: "Premium Wireless Headphones", slug: "premium-wireless-headphones",
        description: "High-quality noise-canceling wireless headphones.",
        price: 249.99, compare_at_price: 299.99, currency: "USD",
        stock_quantity: 45, status: "active", condition: "new", is_featured: true, is_digital: false, requires_shipping: true,
        view_count: 1250, sales_count: 340, average_rating: 4.8, review_count: 128,
        attributes: {}, tags: ["electronics", "audio"],
        seller_id: "s1", seller_name: "Tech Haven", seller_slug: "tech-haven", seller_rating: 4.9,
        category_id: "cat-1", category_name: "Electronics",
        images: [], variants: [], reviews: [],
        primary_image: "assets/images/products/headphones.png",
        created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
        is_in_stock: true, discount_percentage: 16,
      },
      {
        id: "prod-2", title: "Minimalist Smartwatch", slug: "minimalist-smartwatch",
        description: "Track your fitness and stay connected with this sleek smartwatch.",
        price: 199.50, compare_at_price: undefined, currency: "USD",
        stock_quantity: 20, status: "active", condition: "new", is_featured: true, is_digital: false, requires_shipping: true,
        view_count: 850, sales_count: 120, average_rating: 4.6, review_count: 84,
        attributes: {}, tags: ["electronics", "wearables"],
        seller_id: "s1", seller_name: "Tech Haven", seller_slug: "tech-haven", seller_rating: 4.9,
        category_id: "cat-1", category_name: "Electronics",
        images: [], variants: [], reviews: [],
        primary_image: "assets/images/products/smartwatch.png",
        created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
        is_in_stock: true, discount_percentage: 0,
      },
      {
        id: "prod-3", title: "Professional DSLR Camera", slug: "pro-dslr-camera",
        description: "Capture stunning photos and 4K video.",
        price: 899.00, compare_at_price: 1050.00, currency: "USD",
        stock_quantity: 5, status: "active", condition: "new", is_featured: true, is_digital: false, requires_shipping: true,
        view_count: 3200, sales_count: 45, average_rating: 4.9, review_count: 210,
        attributes: {}, tags: ["electronics", "camera"],
        seller_id: "s1", seller_name: "Tech Haven", seller_slug: "tech-haven", seller_rating: 4.9,
        category_id: "cat-1", category_name: "Electronics",
        images: [], variants: [], reviews: [],
        primary_image: "assets/images/products/dslr.png",
        created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
        is_in_stock: true, discount_percentage: 14,
      },
      {
        id: "prod-4", title: "4K LED Creator Monitor", slug: "4k-led-monitor",
        description: "Ultra-wide color gamut monitor for creative professionals.",
        price: 450.00, compare_at_price: 500.00, currency: "USD",
        stock_quantity: 12, status: "active", condition: "new", is_featured: false, is_digital: false, requires_shipping: true,
        view_count: 800, sales_count: 55, average_rating: 4.5, review_count: 42,
        attributes: {}, tags: ["electronics", "monitor"],
        seller_id: "s1", seller_name: "Tech Haven", seller_slug: "tech-haven", seller_rating: 4.9,
        category_id: "cat-1", category_name: "Electronics",
        images: [], variants: [], reviews: [],
        primary_image: "https://images.unsplash.com/photo-1547115941-bb84f5f60600?q=80&w=800&auto=format&fit=crop",
        created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
        is_in_stock: true, discount_percentage: 10,
      },
      {
        id: "prod-5", title: "Mechanical Keycap Keyboard", slug: "mech-keyboard",
        description: "Tactile mechanical keyboard with customized keycaps.",
        price: 120.00, compare_at_price: undefined, currency: "USD",
        stock_quantity: 80, status: "active", condition: "new", is_featured: false, is_digital: false, requires_shipping: true,
        view_count: 2000, sales_count: 400, average_rating: 4.9, review_count: 150,
        attributes: {}, tags: ["electronics", "peripherals"],
        seller_id: "s1", seller_name: "Tech Haven", seller_slug: "tech-haven", seller_rating: 4.9,
        category_id: "cat-1", category_name: "Electronics",
        images: [], variants: [], reviews: [],
        primary_image: "https://images.unsplash.com/photo-1595225476474-87563907a212?q=80&w=1000&auto=format&fit=crop",
        created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
        is_in_stock: true, discount_percentage: 0,
      },
      {
        id: "prod-6", title: "Wireless Gaming Mouse", slug: "wireless-mouse",
        description: "Zero latency competitive gaming mouse.",
        price: 89.99, compare_at_price: 110.00, currency: "USD",
        stock_quantity: 45, status: "active", condition: "new", is_featured: false, is_digital: false, requires_shipping: true,
        view_count: 1500, sales_count: 200, average_rating: 4.7, review_count: 90,
        attributes: {}, tags: ["electronics", "peripherals"],
        seller_id: "s1", seller_name: "Tech Haven", seller_slug: "tech-haven", seller_rating: 4.9,
        category_id: "cat-1", category_name: "Electronics",
        images: [], variants: [], reviews: [],
        primary_image: "https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?q=80&w=1000&auto=format&fit=crop",
        created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
        is_in_stock: true, discount_percentage: 18,
      },
      {
        id: "prod-7", title: "Portable SSD 1TB", slug: "portable-ssd",
        description: "High speed external storage drive.",
        price: 150.00, compare_at_price: undefined, currency: "USD",
        stock_quantity: 200, status: "active", condition: "new", is_featured: true, is_digital: false, requires_shipping: true,
        view_count: 500, sales_count: 180, average_rating: 4.9, review_count: 65,
        attributes: {}, tags: ["electronics", "storage"],
        seller_id: "s1", seller_name: "Tech Haven", seller_slug: "tech-haven", seller_rating: 4.9,
        category_id: "cat-1", category_name: "Electronics",
        images: [], variants: [], reviews: [],
        primary_image: "https://images.unsplash.com/photo-1517430816045-df4b7de11d1d?q=80&w=800&auto=format&fit=crop",
        created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
        is_in_stock: true, discount_percentage: 0,
      },

      // Seller 2: Urban Threads (s2) - Fashion & Beauty
      {
        id: "prod-8", title: "Athletic Running Shoes", slug: "athletic-running-shoes",
        description: "Lightweight and breathable running shoes.",
        price: 129.99, compare_at_price: undefined, currency: "USD",
        stock_quantity: 120, status: "active", condition: "new", is_featured: true, is_digital: false, requires_shipping: true,
        view_count: 4500, sales_count: 890, average_rating: 4.5, review_count: 345,
        attributes: {}, tags: ["fashion", "shoes"],
        seller_id: "s2", seller_name: "Urban Threads", seller_slug: "urban-threads", seller_rating: 4.7,
        category_id: "cat-2", category_name: "Fashion Area",
        images: [], variants: [], reviews: [],
        primary_image: "assets/images/products/shoes.png",
        created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
        is_in_stock: true, discount_percentage: 0,
      },
      {
        id: "prod-9", title: "Vintage Sunglasses", slug: "vintage-sunglasses",
        description: "Classic UV400 protection sunglasses.",
        price: 45.00, compare_at_price: 60.00, currency: "USD",
        stock_quantity: 80, status: "active", condition: "new", is_featured: true, is_digital: false, requires_shipping: true,
        view_count: 1500, sales_count: 420, average_rating: 4.7, review_count: 156,
        attributes: {}, tags: ["fashion", "accessories"],
        seller_id: "s2", seller_name: "Urban Threads", seller_slug: "urban-threads", seller_rating: 4.7,
        category_id: "cat-2", category_name: "Fashion Area",
        images: [], variants: [], reviews: [],
        primary_image: "assets/images/products/sunglasses.png",
        created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
        is_in_stock: true, discount_percentage: 25,
      },
      {
        id: "prod-10", title: "Waterproof Travel Backpack", slug: "waterproof-backpack",
        description: "Durable backpack for everyday use and travel.",
        price: 85.00, compare_at_price: undefined, currency: "USD",
        stock_quantity: 35, status: "active", condition: "new", is_featured: true, is_digital: false, requires_shipping: true,
        view_count: 2100, sales_count: 210, average_rating: 4.8, review_count: 98,
        attributes: {}, tags: ["fashion", "bags"],
        seller_id: "s2", seller_name: "Urban Threads", seller_slug: "urban-threads", seller_rating: 4.7,
        category_id: "cat-2", category_name: "Fashion Area",
        images: [], variants: [], reviews: [],
        primary_image: "assets/images/products/backpack.png",
        created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
        is_in_stock: true, discount_percentage: 0,
      },
      {
        id: "prod-11", title: "Denim Trucker Jacket", slug: "denim-jacket",
        description: "Classic fit washed denim jacket.",
        price: 90.00, compare_at_price: 110.00, currency: "USD",
        stock_quantity: 40, status: "active", condition: "new", is_featured: false, is_digital: false, requires_shipping: true,
        view_count: 3000, sales_count: 150, average_rating: 4.6, review_count: 75,
        attributes: {}, tags: ["fashion", "clothing"],
        seller_id: "s2", seller_name: "Urban Threads", seller_slug: "urban-threads", seller_rating: 4.7,
        category_id: "cat-2", category_name: "Fashion Area",
        images: [], variants: [], reviews: [],
        primary_image: "https://images.unsplash.com/photo-1567361899017-d5d36e2f1f1d?q=80&w=800&auto=format&fit=crop",
        created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
        is_in_stock: true, discount_percentage: 18,
      },
      {
        id: "prod-12", title: "Cotton Basic Tee", slug: "cotton-tee",
        description: "100% organic cotton everyday t-shirt.",
        price: 25.00, compare_at_price: undefined, currency: "USD",
        stock_quantity: 400, status: "active", condition: "new", is_featured: false, is_digital: false, requires_shipping: true,
        view_count: 8000, sales_count: 2400, average_rating: 4.9, review_count: 500,
        attributes: {}, tags: ["fashion", "clothing"],
        seller_id: "s2", seller_name: "Urban Threads", seller_slug: "urban-threads", seller_rating: 4.7,
        category_id: "cat-2", category_name: "Fashion Area",
        images: [], variants: [], reviews: [],
        primary_image: "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?q=80&w=1000&auto=format&fit=crop",
        created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
        is_in_stock: true, discount_percentage: 0,
      },
      {
        id: "prod-13", title: "Organic Skin Serum", slug: "skin-serum",
        description: "Vitamin C and Hyaluronic Acid daily glow serum.",
        price: 55.00, compare_at_price: 70.00, currency: "USD",
        stock_quantity: 90, status: "active", condition: "new", is_featured: true, is_digital: false, requires_shipping: true,
        view_count: 4200, sales_count: 850, average_rating: 4.8, review_count: 320,
        attributes: {}, tags: ["beauty", "skincare"],
        seller_id: "s2", seller_name: "Urban Threads", seller_slug: "urban-threads", seller_rating: 4.7,
        category_id: "cat-4", category_name: "Beauty",
        images: [], variants: [], reviews: [],
        primary_image: "https://images.unsplash.com/photo-1620916566398-39f1143ab7be?q=80&w=1000&auto=format&fit=crop",
        created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
        is_in_stock: true, discount_percentage: 21,
      },
      {
        id: "prod-14", title: "Hydrating Facial Cleanser", slug: "facial-cleanser",
        description: "Gentle daily foaming cleanser for sensitive skin.",
        price: 30.00, compare_at_price: undefined, currency: "USD",
        stock_quantity: 150, status: "active", condition: "new", is_featured: false, is_digital: false, requires_shipping: true,
        view_count: 2100, sales_count: 500, average_rating: 4.7, review_count: 180,
        attributes: {}, tags: ["beauty", "skincare"],
        seller_id: "s2", seller_name: "Urban Threads", seller_slug: "urban-threads", seller_rating: 4.7,
        category_id: "cat-4", category_name: "Beauty",
        images: [], variants: [], reviews: [],
        primary_image: "https://images.unsplash.com/photo-1556228578-0d85b1a4d571?q=80&w=1000&auto=format&fit=crop",
        created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
        is_in_stock: true, discount_percentage: 0,
      },

      // Seller 3: Home Essentials (s3) - Home, Toys, Sports
      {
        id: "prod-15", title: "Modern Coffee Maker", slug: "modern-coffee-maker",
        description: "Start your day right with perfect coffee. Includes frother.",
        price: 149.99, compare_at_price: 199.99, currency: "USD",
        stock_quantity: 15, status: "active", condition: "new", is_featured: true, is_digital: false, requires_shipping: true,
        view_count: 3400, sales_count: 512, average_rating: 4.6, review_count: 231,
        attributes: {}, tags: ["home", "appliances"],
        seller_id: "s3", seller_name: "Home Essentials", seller_slug: "home-essentials", seller_rating: 4.6,
        category_id: "cat-3", category_name: "Home & Kitchen",
        images: [], variants: [], reviews: [],
        primary_image: "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?q=80&w=800&auto=format&fit=crop",
        created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
        is_in_stock: true, discount_percentage: 25,
      },
      {
        id: "prod-16", title: "Linen Throw Blanket", slug: "linen-throw",
        description: "Soft breathable linen throw for couch or bed.",
        price: 45.00, compare_at_price: undefined, currency: "USD",
        stock_quantity: 80, status: "active", condition: "new", is_featured: false, is_digital: false, requires_shipping: true,
        view_count: 1200, sales_count: 310, average_rating: 4.8, review_count: 95,
        attributes: {}, tags: ["home", "decor"],
        seller_id: "s3", seller_name: "Home Essentials", seller_slug: "home-essentials", seller_rating: 4.6,
        category_id: "cat-3", category_name: "Home & Kitchen",
        images: [], variants: [], reviews: [],
        primary_image: "https://images.unsplash.com/photo-1543157145-f78c636d023d?q=80&w=800&auto=format&fit=crop",
        created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
        is_in_stock: true, discount_percentage: 0,
      },
      {
        id: "prod-17", title: "Ceramic Plate Set", slug: "ceramic-plates",
        description: "Handcrafted unglazed ceramic plates, set of 4.",
        price: 65.00, compare_at_price: 80.00, currency: "USD",
        stock_quantity: 30, status: "active", condition: "new", is_featured: false, is_digital: false, requires_shipping: true,
        view_count: 2400, sales_count: 180, average_rating: 4.9, review_count: 110,
        attributes: {}, tags: ["home", "kitchen"],
        seller_id: "s3", seller_name: "Home Essentials", seller_slug: "home-essentials", seller_rating: 4.6,
        category_id: "cat-3", category_name: "Home & Kitchen",
        images: [], variants: [], reviews: [],
        primary_image: "https://images.unsplash.com/photo-1594913215266-963db874aae6?q=80&w=800&auto=format&fit=crop",
        created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
        is_in_stock: true, discount_percentage: 18,
      },
      {
        id: "prod-18", title: "Yoga Mat with Alignment Lines", slug: "yoga-mat",
        description: "Non-slip eco-friendly yoga mat.",
        price: 35.00, compare_at_price: undefined, currency: "USD",
        stock_quantity: 150, status: "active", condition: "new", is_featured: true, is_digital: false, requires_shipping: true,
        view_count: 5000, sales_count: 1200, average_rating: 4.8, review_count: 400,
        attributes: {}, tags: ["sports", "fitness"],
        seller_id: "s3", seller_name: "Home Essentials", seller_slug: "home-essentials", seller_rating: 4.6,
        category_id: "cat-5", category_name: "Sports",
        images: [], variants: [], reviews: [],
        primary_image: "https://images.unsplash.com/photo-1575052814086-f385e2e2ad1b?q=80&w=1000&auto=format&fit=crop",
        created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
        is_in_stock: true, discount_percentage: 0,
      },
      {
        id: "prod-19", title: "Resistance Band Set", slug: "resistance-bands",
        description: "Set of 5 heavy duty workout bands with handles.",
        price: 24.99, compare_at_price: 35.00, currency: "USD",
        stock_quantity: 400, status: "active", condition: "new", is_featured: false, is_digital: false, requires_shipping: true,
        view_count: 3200, sales_count: 1800, average_rating: 4.6, review_count: 550,
        attributes: {}, tags: ["sports", "fitness"],
        seller_id: "s3", seller_name: "Home Essentials", seller_slug: "home-essentials", seller_rating: 4.6,
        category_id: "cat-5", category_name: "Sports",
        images: [], variants: [], reviews: [],
        primary_image: "https://images.unsplash.com/photo-1541534741688-6078c64b52d3?q=80&w=800&auto=format&fit=crop",
        created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
        is_in_stock: true, discount_percentage: 28,
      },
      {
        id: "prod-20", title: "Educational Building Blocks", slug: "building-blocks",
        description: "100-piece wooden block set for children.",
        price: 49.99, compare_at_price: undefined, currency: "USD",
        stock_quantity: 60, status: "active", condition: "new", is_featured: true, is_digital: false, requires_shipping: true,
        view_count: 1800, sales_count: 450, average_rating: 4.9, review_count: 210,
        attributes: {}, tags: ["toys", "kids"],
        seller_id: "s3", seller_name: "Home Essentials", seller_slug: "home-essentials", seller_rating: 4.6,
        category_id: "cat-6", category_name: "Toys & Games",
        images: [], variants: [], reviews: [],
        primary_image: "https://images.unsplash.com/photo-1587654780291-39c9404d746b?q=80&w=800&auto=format&fit=crop",
        created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
        is_in_stock: true, discount_percentage: 0,
      },
      {
        id: "prod-21", title: "Family Board Game Night", slug: "board-game",
        description: "Strategy and fun for the whole family.",
        price: 29.99, compare_at_price: 39.99, currency: "USD",
        stock_quantity: 120, status: "active", condition: "new", is_featured: false, is_digital: false, requires_shipping: true,
        view_count: 2200, sales_count: 600, average_rating: 4.8, review_count: 180,
        attributes: {}, tags: ["toys", "games"],
        seller_id: "s3", seller_name: "Home Essentials", seller_slug: "home-essentials", seller_rating: 4.6,
        category_id: "cat-6", category_name: "Toys & Games",
        images: [], variants: [], reviews: [],
        primary_image: "https://images.unsplash.com/photo-1632501641765-e568d28b0015?q=80&w=1000&auto=format&fit=crop",
        created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
        is_in_stock: true, discount_percentage: 25,
      },

      // Seller 4: Green Thumb Gardens (s4) - Home/Garden & Assorted
      {
        id: "prod-22", title: "Monstera Deliciosa Plant", slug: "monstera-deliciosa",
        description: "Beautiful indoor plant with iconic split leaves. Perfect for any home.",
        price: 45.00, compare_at_price: 55.00, currency: "USD",
        stock_quantity: 40, status: "active", condition: "new", is_featured: true, is_digital: false, requires_shipping: true,
        view_count: 5600, sales_count: 1200, average_rating: 4.8, review_count: 310,
        attributes: {}, tags: ["garden", "plants", "indoor"],
        seller_id: "s4", seller_name: "Green Thumb Gardens", seller_slug: "green-thumb", seller_rating: 4.8,
        category_id: "cat-7", category_name: "Garden",
        images: [], variants: [], reviews: [],
        primary_image: "https://images.unsplash.com/photo-1614594975525-e45190c55d0b?q=80&w=800&auto=format&fit=crop",
        created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
        is_in_stock: true, discount_percentage: 18,
      },
      {
        id: "prod-23", title: "Fiddle Leaf Fig", slug: "fiddle-leaf-fig",
        description: "Tall statement plant with large violin-shaped leaves.",
        price: 85.00, compare_at_price: undefined, currency: "USD",
        stock_quantity: 15, status: "active", condition: "new", is_featured: true, is_digital: false, requires_shipping: true,
        view_count: 4200, sales_count: 300, average_rating: 4.6, review_count: 145,
        attributes: {}, tags: ["garden", "plants", "indoor"],
        seller_id: "s4", seller_name: "Green Thumb Gardens", seller_slug: "green-thumb", seller_rating: 4.8,
        category_id: "cat-7", category_name: "Garden",
        images: [], variants: [], reviews: [],
        primary_image: "https://images.unsplash.com/photo-1592150621344-afed8b638a5a?q=80&w=800&auto=format&fit=crop",
        created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
        is_in_stock: true, discount_percentage: 0,
      },
      {
        id: "prod-24", title: "Succulent Assortment", slug: "succulent-pack",
        description: "Pack of 6 different low-maintenance succulents.",
        price: 25.00, compare_at_price: 35.00, currency: "USD",
        stock_quantity: 100, status: "active", condition: "new", is_featured: false, is_digital: false, requires_shipping: true,
        view_count: 6000, sales_count: 1500, average_rating: 4.9, review_count: 620,
        attributes: {}, tags: ["garden", "plants", "small"],
        seller_id: "s4", seller_name: "Green Thumb Gardens", seller_slug: "green-thumb", seller_rating: 4.8,
        category_id: "cat-7", category_name: "Garden",
        images: [], variants: [], reviews: [],
        primary_image: "https://images.unsplash.com/photo-1459411552884-841db9b3cc2a?q=80&w=800&auto=format&fit=crop",
        created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
        is_in_stock: true, discount_percentage: 28,
      },
      {
        id: "prod-25", title: "Indoor Plant Food Liquid", slug: "plant-food",
        description: "Organic liquid fertilizer for dark green growth.",
        price: 15.00, compare_at_price: undefined, currency: "USD",
        stock_quantity: 300, status: "active", condition: "new", is_featured: false, is_digital: false, requires_shipping: true,
        view_count: 2000, sales_count: 800, average_rating: 4.5, review_count: 230,
        attributes: {}, tags: ["garden", "supplies"],
        seller_id: "s4", seller_name: "Green Thumb Gardens", seller_slug: "green-thumb", seller_rating: 4.8,
        category_id: "cat-7", category_name: "Garden",
        images: [], variants: [], reviews: [],
        primary_image: "https://images.unsplash.com/photo-1621328070209-416585778844?q=80&w=800&auto=format&fit=crop",
        created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
        is_in_stock: true, discount_percentage: 0,
      },
      {
        id: "prod-26", title: "Aromatherapy Essential Oil Roll", slug: "essential-oil",
        description: "Lavender and eucalyptus organic roll on.",
        price: 18.00, compare_at_price: 24.00, currency: "USD",
        stock_quantity: 120, status: "active", condition: "new", is_featured: false, is_digital: false, requires_shipping: true,
        view_count: 1100, sales_count: 320, average_rating: 4.8, review_count: 90,
        attributes: {}, tags: ["beauty", "wellness"],
        seller_id: "s4", seller_name: "Green Thumb Gardens", seller_slug: "green-thumb", seller_rating: 4.8,
        category_id: "cat-4", category_name: "Beauty",
        images: [], variants: [], reviews: [],
        primary_image: "https://images.unsplash.com/photo-1620916566398-39f1143ab7be?q=80&w=800&auto=format&fit=crop",
        created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
        is_in_stock: true, discount_percentage: 25,
      },
      {
        id: "prod-27", title: "Ergonomic Hand Trowel", slug: "ergonomic-trowel",
        description: "Stainless steel hand trowel with a comfortable grip for easy planting.",
        price: 24.50, compare_at_price: 29.99, currency: "USD",
        stock_quantity: 45, status: "active", condition: "new", is_featured: false, is_digital: false, requires_shipping: true,
        view_count: 850, sales_count: 120, average_rating: 4.8, review_count: 42,
        attributes: {}, tags: ["garden", "tools"],
        seller_id: "s4", seller_name: "Green Thumb Gardens", seller_slug: "green-thumb", seller_rating: 4.8,
        category_id: "cat-7", category_name: "Garden",
        images: [], variants: [], reviews: [],
        primary_image: "https://images.unsplash.com/photo-1671981248981-2a628373b747?q=80&w=800&auto=format&fit=crop",
        created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
        is_in_stock: true, discount_percentage: 18,
      },
      {
        id: "prod-28", title: "Bamboo Plant Stand", slug: "bamboo-plant-stand",
        description: "Sustainable multi-tier bamboo stand for displaying your indoor plant collection.",
        price: 65.00, compare_at_price: 85.00, currency: "USD",
        stock_quantity: 20, status: "active", condition: "new", is_featured: true, is_digital: false, requires_shipping: true,
        view_count: 1200, sales_count: 45, average_rating: 4.9, review_count: 18,
        attributes: {}, tags: ["garden", "decor", "indoor"],
        seller_id: "s4", seller_name: "Green Thumb Gardens", seller_slug: "green-thumb", seller_rating: 4.8,
        category_id: "cat-7", category_name: "Garden",
        images: [], variants: [], reviews: [],
        primary_image: "https://images.unsplash.com/photo-1592178036219-5415ef4eb806?q=80&w=800&auto=format&fit=crop",
        created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
        is_in_stock: true, discount_percentage: 24,
      }
    ];
  }

  getProductBySlug(slug: string): Observable<Product> {
    return this.getFeaturedProducts(100).pipe(
      map((products: Product[]) => {
        const product = products.find((p: Product) => p.slug === slug);
        if (!product) {
          throw new Error('Product not found');
        }
        return product;
      })
    );
  }

  getCategories(): Observable<Category[]> {
    const products = this.getSampleProducts();
    const categories: Category[] = [
      { id: "cat-1", name: "Electronics", slug: "electronics", icon: "devices", level: 0, sort_order: 1, is_active: true, is_featured: true, product_count: 0, image_url: 'https://images.unsplash.com/photo-1498049794561-7780e7231661?q=80&w=800&auto=format&fit=crop' },
      { id: "cat-2", name: "Fashion Area", slug: "fashion", icon: "checkroom", level: 0, sort_order: 2, is_active: true, is_featured: true, product_count: 0, image_url: 'https://images.unsplash.com/photo-1483985988355-763728e1935b?q=80&w=800&auto=format&fit=crop' },
      { id: "cat-3", name: "Home & Kitchen", slug: "home", icon: "kitchen", level: 0, sort_order: 3, is_active: true, is_featured: true, product_count: 0, image_url: 'https://images.unsplash.com/photo-1556911220-e15b29be8c8f?q=80&w=800&auto=format&fit=crop' },
      { id: "cat-4", name: "Beauty", slug: "beauty", icon: "face", level: 0, sort_order: 4, is_active: true, is_featured: true, product_count: 0, image_url: 'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?q=80&w=800&auto=format&fit=crop' },
      { id: "cat-5", name: "Sports", slug: "sports", icon: "sports_basketball", level: 0, sort_order: 5, is_active: true, is_featured: true, product_count: 0, image_url: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?q=80&w=800&auto=format&fit=crop' },
      { id: "cat-6", name: "Toys & Games", slug: "toys", icon: "toys", level: 0, sort_order: 6, is_active: true, is_featured: true, product_count: 0, image_url: 'https://images.unsplash.com/photo-1545558014-8692077e9b5c?q=80&w=800&auto=format&fit=crop' },
      { id: "cat-7", name: "Garden", slug: "garden", icon: "yard", level: 0, sort_order: 7, is_active: true, is_featured: true, product_count: 0, image_url: 'https://images.unsplash.com/photo-1585320806297-9794b3e4eeae?q=80&w=800&auto=format&fit=crop' },
    ];

    const finalCategories = categories.map(cat => ({
      ...cat,
      product_count: products.filter(p => p.category_id === cat.id).length
    }));

    return of(finalCategories);
  }
}
